# Site settings
site: Zahra
title: Zahra Abbasgholi
# keywords: ephesus, blog
# description: >-
#   Ephesus - Minimalist Jekyll Theme
lang: en-US
timezone:  Asia/Tehran
repo: https://zahraabbasgholi.github.io/labexam # site repo [optional]
google_verify:      XXX # Put your Google Verification here
google_analytics:   UA-XXXXXXXX-00 # Put your Google Analytics code
discus-identifier:  XXX

# Author settings
author:
  name: Zahra Abbasgholi
  bio: I'm student of Computer Engineering
  picture: assets/images/profile.jpg 
  github: https://github.com/ZahraAbbasgholi # github username
  # twitter: onepase # twitter username
  # facebook: onepase # facebook username
  # instagram: onepase # instagram username
  # youtube: https://www.youtube.com/channel/UCMmAto-wxBootXN91AzBiDg # youtube username
  # linkedin: hakantorun # linkedin username
  email: z.abbasgholi10@email.com # email adress


# URL settings
url: "https://zahraabbasgholi.github.io" # Domain Name of host. [username].github.io for github pages
permalink: labexam

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false